-- migrate:up
SET ROLE = law_admin;

-- Give cap.opinions a primary key (issue #74).
--
-- The table has had no key and no index since the import: an opinion was
-- reached through its case, and nothing in the project addressed one on its
-- own. Detecting citations in the opinions (cite-detector-cap) needs to,
-- because opinion_citations.citations_unlinked records the opinion each
-- citation was found in, and ("case", type) does not identify one. Measured
-- 2026-09-26 on a 1% block sample (TABLESAMPLE SYSTEM (1)): 77,848 rows held
-- 77,399 distinct ("case", type) pairs, 449 rows over, and the surplus falls
-- in every type (154 duplicated pairs of dissents, 100 of concurrences, 53
-- of majorities, 33 concurring-in-part-and-dissenting-in-part, 24
-- rehearings); case 6208386 carries five opinions typed concurrence. So a
-- surrogate id, not a composite key.
--
-- The id is added by backfill, not by ADD COLUMN ... GENERATED AS IDENTITY.
-- An identity column's default is volatile (nextval), so adding one rewrites
-- the whole table, and cap.opinions is 38 GB, of which 36 GB is the TOASTed
-- text and 2.9 GB the heap (7,815,828 rows in 367,168 pages). Adding a bare
-- nullable bigint is a catalog change; the UPDATE that fills it writes a new
-- version of each of the 7.8M heap tuples, about 2.9 GB, and never touches
-- TOAST, because the text is stored out of line and the new tuple version
-- keeps the old TOAST pointer. The identity is attached afterwards, when the
-- column is already full, and its sequence is set past the largest id, so
-- new rows take the default from then on.
--
-- ESTIMATES, to be replaced by the measured figures once applied: about ten
-- minutes under the ACCESS EXCLUSIVE lock, roughly 6 GB of WAL (the new
-- tuple versions and the two indexes), and a heap that stays at about 5.8 GB
-- on disk afterwards, because VACUUM makes the dead half reusable but does
-- not shrink the file. In a local rehearsal on 426 rows (with duplicate
-- ("case", type) pairs) the up's statements took 5 ms together and the
-- down's 1.4 ms; the figures say nothing about the 7.8M-row table beyond
-- the DDL being right, up and down, and a rerun of either being a no-op.
--
-- Whom the lock affects: cap-import, the only writer, which inserts by
-- column list (cap-import/db.go:70-73) and so needs no change, and any ad
-- hoc reader of cap.opinions. The MOML detector and linker never touch the
-- table, so a MOML pipeline run is not in the way. lock_timeout makes the
-- migration fail fast behind an idle reader instead of queueing every later
-- request on the table behind it; rerun it once the reader is gone.
--
-- After `make db-up`, run by hand, because VACUUM cannot run inside the
-- migration's transaction:
--
--   VACUUM (ANALYZE, PROCESS_TOAST false) cap.opinions;
--
-- It marks the 7.8M dead tuple versions reusable and sets the visibility
-- map; PROCESS_TOAST false spares the 36 GB TOAST table, which the UPDATE
-- did not change.
SET lock_timeout = '1min';

-- Metadata only: no default, so no rewrite.
ALTER TABLE cap.opinions ADD COLUMN IF NOT EXISTS id bigint;

-- Fill the column from a throwaway sequence: heap only, TOAST untouched. A
-- rerun finds no NULLs and writes nothing.
CREATE SEQUENCE IF NOT EXISTS cap.opinions_id_backfill;
UPDATE cap.opinions SET id = nextval('cap.opinions_id_backfill') WHERE id IS NULL;
DROP SEQUENCE IF EXISTS cap.opinions_id_backfill;

ALTER TABLE cap.opinions ALTER COLUMN id SET NOT NULL;

-- Build the unique index, then promote it to the primary key, so that a
-- rerun finds both in place and does neither again.
CREATE UNIQUE INDEX IF NOT EXISTS opinions_pkey ON cap.opinions (id);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'cap.opinions'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE cap.opinions
      ADD CONSTRAINT opinions_pkey PRIMARY KEY USING INDEX opinions_pkey;
  END IF;
END $$;

-- Attach the identity now that the column is full, so the sequence it
-- creates is never run over the table. attidentity is '' for a plain
-- column, 'd' for GENERATED BY DEFAULT and 'a' for ALWAYS.
DO $$
BEGIN
  IF (SELECT attidentity FROM pg_attribute
      WHERE attrelid = 'cap.opinions'::regclass AND attname = 'id') = '' THEN
    ALTER TABLE cap.opinions
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- The next default id is max(id) + 1. On an empty table max(id) is NULL and
-- setval does nothing, which leaves the fresh sequence at its start.
SELECT setval(pg_get_serial_sequence('cap.opinions', 'id'),
              (SELECT max(id) FROM cap.opinions));

-- Supports the foreign key from "case" and per-case lookups. The detector's
-- stream joins cap.cases from the opinion side and does not need it.
CREATE INDEX IF NOT EXISTS opinions_case_idx ON cap.opinions ("case");

COMMENT ON COLUMN cap.opinions.id IS 'Surrogate key added by migration 20260926130000 (issue #74): ("case", type) is not unique, a case can carry several opinions of one type. Backfilled in heap order; new rows take the identity default.';

ANALYZE cap.opinions;

-- migrate:down
SET ROLE = law_admin;

-- Dropping the column alone would take the key and the identity with it;
-- they are named so the rollback reads as the reverse of the up. The table
-- that references cap.opinions(id), opinion_citations.citations_unlinked, is
-- dropped by its own later migration, which dbmate rolls back first.
DROP INDEX IF EXISTS cap.opinions_case_idx;
ALTER TABLE cap.opinions DROP CONSTRAINT IF EXISTS opinions_pkey;
-- DROP IDENTITY IF EXISTS still needs the column to exist; guard it so a
-- repeated down is a no-op like a repeated up.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'cap.opinions'::regclass AND attname = 'id'
      AND NOT attisdropped
  ) THEN
    ALTER TABLE cap.opinions ALTER COLUMN id DROP IDENTITY IF EXISTS;
  END IF;
END $$;
ALTER TABLE cap.opinions DROP COLUMN IF EXISTS id;
